### PR TITLE
Travis ci docs

### PR DESCRIPTION
**Pull request by misprit7**
Did three main things: 
1. Added Travis-CI short documentation md file as high level overview of travis and how to use it
2. Got rid of warnings on compilation and added some compiler flags including -Werror. This means that warnings are now errors, I'm pretty sure this is good practice to enforce on pushes to master to force good programming, might be wrong there though. 
3. Cleaned up cmake file significantly and changed travis build scripts, since I had misunderstood it before and it had made a bit of a mess. I thought before that we were to execute ```cmake .```, but the actual build directory we want is ```build/```, which meant a bunch of files were getting created that weren't. Deleted these files and updated travis script to build properly. 
Sorry these probably should have been 3 separate pull requests, but too late now. Also branch name is awful.

### CODE REVIEW

**Comment by Esouder** [comment]
Just wanted to add that basically ALL of my CMakeLists.txt files are absolute atrocities; if you figure out what they are supposed to look like I'd be very pleased.

**Comment by misprit7** [comment]
Alright, after doing some debugging on Travis's end I think it should be working now. The issue was I was using some CMake syntax ```build -S .. -B .``` that wasn't available on their (old) version of CMake. I've added a pre-script to update to the latest version of CMake to avoid similar problems in the future and changed that syntax to equivalent just to be sure.

**Comment by misprit7** [comment]
@Esouder if you could review and merge (if everything is fine) that would be great.

**Comment by Esouder** [comment]
@misprit7 Looks great, the documentation is very handy.

**Pull request merged**
