### PR TITLE
Implement states

### PR DESCRIPTION
**Pull request by Esouder**
This adds in the actual states for the state machine, as well as some preliminary logic and state transition inputs. This should close 
 issue #24.

### CODE REVIEW

**Comment by misprit7** [comment]
I'm kind of personally offended about this naming convention: 
```c
char HMI_triggerGroundAbort; //holy snake-camel, Batman!
char HMI_triggerStandby;
char HMI_triggerFueling;
```
That being said your comment explaining your justification almost makes up for it.

**Comment by Esouder** [comment]
Yes, I grossed myself out there - but it's kind of grown on me, you know? and it seemed slightly clearer than `HMITrigger...` and les gross that `hmiTrigger`

**Comment by misprit7** [comment]
In all seriousness, a couple of notes: 
- In the state transition functions, after you check for the triggers we want some way of resetting them. For example once we transition from fueling to standby we don't want the HMI_triggerStandby to be left on. 
- We should have some way of initializing the stateInput so it's members don't just start at random values. 
- Now that we have some actual states implemented, we should definitely add some tests. @Esouder can you add some unit tests that test the system by initializing the state input, feeding it into the machine and making sure everything works out as expected? Ideally every possible branch would be tested, although since some of them are still placeholders that probably won't be possible right now. 

Overall all though looks great, the transition table looks super clean and it matches as far as I can tell with the spreadsheet.

**Comment by Esouder** [comment]
Great points 

1- I kind of assumed that this would be handled by whatever actuated the trigger in the first place, but it should probably be in the state transition function.

3 - There's one (brief) version of this, but I can add some more that expand on it.

**Comment by misprit7** [comment]
That's my bad I didn't check the test file for some reason. That being said it should probably be expanded, right now it's only testing a few states and ideally the test(s) would be more comprehensive than this. Also as I mentioned be careful to initialize the state input in both the tests and WhistlerBlackcomb.c as right now it has properties being assigned to before it has been initialized. It's actually a lot easier than I thought: https://en.cppreference.com/w/c/language/struct_initialization

**Comment by misprit7** [comment]
Also I just realized for some reason the SIM connection isn't outputting the SYN/ACK initialization right now, but it is on master. I'm not really sure what changed (from what I can tell the output/input task is being initialized but it's just not running), @Esouder you might want to check this and see if it's just an issue on my end.

**Comment by Esouder** [comment]
Oops, didn't include a delay in the state transition task. Fixed in commit 4435fa4.

**Comment by Esouder** [comment]
I've added a test that I think tests all the possible transitions. 

For initializing to zero and resetting the flags - I've put the initialization _inside_ the the loop, so it should reset everything to zero every loop through. Is there a lot of overhead associated with this?

**Comment by misprit7** [comment]
The input should not be reset every loop. Remember other tasks have to update the state input like the HMI input, but if it's being reset there would have to be another dummy variable to keep track of that which doesn't really make sense.

**Comment by Esouder** [comment]
If anyone has better name suggestions for `examplePathTest()` I would like to know.

**Pull request merged**
